spring:
  profiles:
    active:
      -dev
---
spring:
     profiles: dev
     application:
       name: microservicecloud-cloud-config-dev
---
spring:
     profiles: dev
     application:
        name: microservicecloud-cloud-config-test